In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('Bengaluru_House_Data.csv')

In [3]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
data.tail()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.0

In [4]:
data.shape

(13320, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
# lets apply Valuecount in every column

for column in data.columns:
    print(data[column].value_counts())
    print('*'*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [7]:
# we will drop Soceity Column . I will tell u why

In [8]:
# lets see how many NULL Value
data.isna().sum()

# see lots of scoceity null value so we gonna drop them
# and we will aslo drop the balcony also

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [9]:
# columns that need to be drop
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [10]:
data.describe()
# we got only 2 numerical column one is bathroom and other is price

# min bathroom is 1. 1st qaurtile 2 bathroom ka , median=2 bathroom, 3rd quartile=3 bathroom
# max bathroom= 40

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [11]:
# after droping info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

# Now lets fillup the missing value one by one

In [12]:
data['location'].value_counts()

# if u can see info its only one missing value.
# total entry=13320
# total non-null=13319
# so koi fark nahi padhta hai humlog kisi bhi value se replace kr sakte hai

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [13]:
# so i will fill 'NA' with sarjapur

data['location']=data['location'].fillna('Sarjapur Road')

In [14]:
# now next step
data['size'].value_counts()
# it has 16 missing value

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [15]:
# sabse zyada 2BHK hai, so we gonna replace missing value with 2bhk
data['size']=data['size'].fillna('2 BHK')

In [16]:
# replce the MIssing value of Bthroom
# we replace it with the median
data['bath']=data['bath'].fillna(data['bath'].median())

In [17]:
data.info()
# now there is no null value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [18]:
# if we notice BHK ka problem theek krna hoga
# size dtype is Object
data['bhk']=data['size'].str.split().str.get(0).astype(int)

# str.split()-->space ke hisaab se split kiya. [because it is string datatype]
# str.get(0)--> phir maine pehla element utha liya which is number in string format
# astype(int)--> jo aaya wo string tha toh astype(int) krke extra column me store kr diya

Your size column looks like this:

size
2 BHK
4 Bedroom
3 BHK
1 Bedroom

👉 Machine learning models cannot understand text like "2 BHK"
They need numbers.

So we extract only the number part → 2, 4, 3, 1
That number is called BHK (number of rooms).

1️⃣ data['size']--->This selects the size column.

2️⃣ data['size'].str

This tells pandas: “Treat each value as a string and allow string operations”

Without .str, string methods won’t work on a column.

3️⃣ .split()
"2 BHK".split() → ['2', 'BHK']
"4 Bedroom".split() → ['4', 'Bedroom']

4️⃣ .str.get(0)
['2', 'BHK'] → '2'
['4', 'Bedroom'] → '4'

This extracts the first element (index 0)
➡️ which is always the number of rooms

5️⃣ .astype(int)
'2' → 2
'4' → 4
Converts the string number into an integer so ML models can use it.

6️⃣ data['bhk'] = ...
Creates a new column called bhk
Final result:
| size      | bhk |
| --------- | --- |
| 2 BHK     | 2   |
| 4 Bedroom | 4   |
| 3 BHK     | 3   |

In [19]:
# new Column Created BHK
data.head(3)

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3

In [20]:
# let me see aisa kaunsa falt hai jisme BHK greator than 20 hai

data[data.bhk > 20]

# these are basically outliers in your data

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [21]:
data['bhk'].unique()

array([ 2,  4,  3,  6,  1,  8,  7,  5, 11,  9, 27, 10, 19, 16, 43, 14, 12,
       13, 18])

In [22]:
data['total_sqft'].unique()
# data me kuch ranges bhi hai--'1133 - 1384', so we gonna fix them
# so iss hyphen ke hisaab se we gonna split and phir dono ka integer value ka mean nikal lenge
# we will do (1133+1384)/2. jahan bhi we get range

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [23]:
# ek function hai jo harr ek value lega and uspar ek split maarega.
# if split hoga and 2 value banega then convert both value into float and then calulate mean
# agar split krne ke baad ek hi value mila than we gonna return float
# so agar float ke conversion me problem hua than we are gonna return none

def convertRange(x):

    temp=x.split('-')
    if len(temp)==2:
        return (float(temp[0]) + float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

🧠 What problem this function solves

Look at the total_sqft column in your dataset.

It contains mixed formats like:
"1056"
"2100 - 2850"
"34.46Sq. Meter"
"3000"

👉 ML models cannot work with mixed text + numbers.
So this function:
✔ Handles ranges like "2100-2850"
✔ Converts clean numbers like "1056"

2️⃣ Split by hyphen
temp = x.split('-')

Examples:
"2100-2850" → ['2100', '2850']
"1056" → ['1056']

3️⃣ Check if it is a range
if len(temp) == 2:
If there are two numbers, it means:
"2100 - 2850"

4️⃣ Take the average of the range
Converts range into single meaningful value

5️⃣ Try converting normal numbers
try:
    return float(x)

If x is already a clean number like "1056"
➡️ Convert it to 1056.0

6️⃣ Handle invalid values safely
except:
    return None

If x is something like:
"34.46Sq. Meter"
"Sq. Yards"

✔ It won’t crash your code
✔ Returns None (later you can drop or fill it)

In [24]:
# now apply this function on total_sqft column

data['total_sqft']=data['total_sqft'].apply(convertRange)

# apply() takes one value at a time from a column and applies a function to it.

# apply function

def square(x):
    return x * x

df = pd.DataFrame({'A': [1, 2, 3, 4]})
df['A'].apply(square)


output:-
1 → 1
2 → 4
3 → 9
4 → 16

In [25]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [ ]:
# make a new column Price per sqaure feet

# price is in lakh

# Price per sqaure feet---price/total_sqft
# so it will come in decimal value so we cona convert it into rupees

In [26]:
data['price_per_sqft']=data['price']*100000/data['total_sqft']

In [27]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [28]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [29]:
data['location'].value_counts()
# Length: 1306 location
# agr we OHE to kitna 1306 column bann jayega. this we cannot pass teh model
# so we have to reduce. Jo bhi location 10 ya usse kam aaya hai we will reduce it to others

location
Whitefield                                      540
Sarjapur  Road                                  399
Electronic City                                 302
Kanakpura Road                                  273
Thanisandra                                     234
                                               ...
Maragondana Halli, kr puram, old madras road      1
Chikkajala                                        1
Udayagiri                                         1
pavitra paradise                                  1
Chikbasavanapura                                  1
Name: count, Length: 1306, dtype: int64

In [30]:
# It removes extra spaces from the beginning and end of every value in the location column.
data['location']=data['location'].apply(lambda x:x.strip())

# ' Whitefield', 'Whitefield ', ' Whitefield '
# After .strip() → all become: 'Whitefield'

In [31]:
location_count=data['location'].value_counts()
location_count

# Length: 1295 my new location

location
Whitefield                541
Sarjapur  Road            399
Electronic City           304
Kanakpura Road            273
Thanisandra               237
                         ...
Xavier Layout               1
Ramanagara Channapatna      1
Maheswari Nagar             1
Hsr layout sector3          1
Thyagraj Nagar              1
Name: count, Length: 1295, dtype: int64

In [32]:
# loaction which occur less than 10 baar

location_count_less_10= location_count[location_count<=10]
location_count_less_10

# Length: 1054 this much entry hai

location
1st Block Koramangala     10
Dairy Circle              10
Nagadevanahalli           10
Sadashiva Nagar           10
Naganathapura             10
                          ..
Xavier Layout              1
Ramanagara Channapatna     1
Maheswari Nagar            1
Hsr layout sector3         1
Thyagraj Nagar             1
Name: count, Length: 1054, dtype: int64

In [33]:
# so we gonna change this location to others

data['location']=data['location'].apply(lambda x:'other' if x in location_count_less_10 else x)
# har location pe check kr rha hai hai ki if that location is in location_count_less_10 we gonna write other there
# nahi toh we gonna write back the location

In [34]:
data['location'].value_counts()
# so we reduce from 1295 to 242
# now if we go OHE so 242 column banega

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

## Deal with OUTLIER and REmoval

In [35]:
data.describe()

# total_sqft=1

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [36]:
# mai ye nikalta hun [total_sqft/ bhk]. like ek bhk me kitne sqft hone chaiye
(data['total_sqft']/data['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [37]:
# so aisa jo bhi flat honge sqft/bhk less than 300 hoga. it is not a feasibile flat

# jahan pe bhi tptal_sqft/bhk > 300 we r gonna keep that
data=data[((data['total_sqft']/data['bhk'])>=300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [38]:
data.shape

(12530, 7)

In [39]:
data.price_per_sqft.describe()
# max value is surely an OUTliers

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [40]:
# so remove this OUTLIER this is my function
def remove_outliers_sqft(df):
    df_output=pd.DataFrame()
    for key,subdf in df.groupby('location'): # group by lagane se ek key milta hai,aur uss key ka subdataframe(subdf)milta hai
        m=np.mean(subdf.price_per_sqft) # subdf me price_per_sqft ka mean nikala

        st=np.std(subdf.price_per_sqft) # standardDeviation

        gen_df=subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))] # using filter on subdf, unhi price ko rakh rha hun jo mean se ek std idhar udar ho, and baki sab prices i am droping
        # iss subdf wo agar m-st and m+st ke under hua i m keeoing them
        df_output=pd.concat([df_output,gen_df],ignore_index=True)
    return df_output
data=remove_outliers_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608      2.471702     91.286372      2.574896     5659.062876
std      880.694214      0.979449     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.897959
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

def remove_outliers_sqft(df):
✔ Creates a function that takes a DataFrame
✔ Purpose: remove abnormal house prices location-wise

df_output = pd.DataFrame()
✔ This will collect filtered rows from all locations

for key, subdf in df.groupby('location'):
This splits data like:

| Location     | Sub DataFrame           |
| ------------ | ----------------------- |
| Whitefield   | All Whitefield houses   |
| Indira Nagar | All Indira Nagar houses |
| Yelahanka    | All Yelahanka houses    |

✔ key → location name
✔ subdf → data for that location only

m = np.mean(subdf.price_per_sqft)
✔ Average price per square foot for that location

st = np.std(subdf.price_per_sqft)
✔ Measures spread / variability in price_per_sqft
✔ High deviation → prices vary a lot


gen_df = subdf[
    (subdf.price_per_sqft > (m - st)) &
    (subdf.price_per_sqft <= (m + st))
]
This keeps only rows:
(mean - 1*std) < price_per_sqft ≤ (mean + 1*std)

📉 Removes:
Very cheap houses (data error / distress sale)
Very expensive houses (luxury anomaly)

📊 Keeps:
Normal, realistic houses

df_output = pd.concat([df_output, gen_df], ignore_index=True)
✔ Adds cleaned data for each location
✔ ignore_index=True resets row numbers

8️⃣ Return cleaned dataset
return df_output

data = remove_outliers_sqft(data)
✔ Replaces original data with cleaned data

🔹 REAL WORLD EXAMPLE
| Location     | Normal Price/sqft |
| ------------ | ----------------- |
| Whitefield   | 5,000–7,000       |
| Indira Nagar | 10,000–15,000     |

If we don’t group:
Indira Nagar prices look like outliers ❌

In [41]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])

    for location, location_df in df.groupby('location'):
        bhk_stats = {}

        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }

        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)

            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.price_per_sqft < stats['mean']].index.values
                )

    return df.drop(exclude_indices, axis='index')

1️⃣ Function definition

def bhk_outlier_remover(df):
✔ Takes a housing DataFrame
✔ Removes illogical BHK price outliers

2️⃣ Container to store bad rows

exclude_indices = np.array([])
✔ Stores row indices that should be deleted
✔ Initially empty

3️⃣ Loop over each location 

for location, location_df in df.groupby('location'):
✔ Work location-wise
✔ location_df contains houses from only one area

👉 This avoids comparing prices across different localities

4️⃣ Dictionary to store BHK statistics

bhk_stats = {}
✔ Will store stats like:
{
  1: {'mean': ..., 'std': ..., 'count': ...},
  2: {'mean': ..., 'std': ..., 'count': ...}
}

5️⃣ Loop over BHKs inside a location

for bhk, bhk_df in location_df.groupby('bhk'):
✔ Now we go BHK-wise
✔ Example: 1 BHK, 2 BHK, 3 BHK in same location

6️⃣ Compute statistics for each BHK
bhk_stats[bhk] = {
    'mean': np.mean(bhk_df.price_per_sqft),
    'std': np.std(bhk_df.price_per_sqft),
    'count': bhk_df.shape[0]
}

Stores:
✔ Average price per sqft
✔ Price variation
✔ Number of samples

Why count?
👉 To ensure statistical reliability

7️⃣ Loop again over BHKs (comparison phase)

for bhk, bhk_df in location_df.groupby('bhk'):
✔ Second pass: now we compare BHKs

8️⃣ Get stats of (BHK − 1)

stats = bhk_stats.get(bhk - 1)
✔ For 2 BHK → get 1 BHK stats
✔ For 3 BHK → get 2 BHK stats

If no smaller BHK exists → None

9️⃣ Validation check

if stats and stats['count'] > 5:
This ensures:
Smaller BHK exists
At least 6 samples (important!)

👉 Avoids decisions based on very small data

🔥 1 0️⃣ CORE OUTLIER LOGIC

bhk_df[bhk_df.price_per_sqft < stats['mean']] 
This finds houses where:
price_per_sqft (current BHK)
<
mean price_per_sqft (smaller BHK)

❌ This is illogical in real estate

1 1️⃣ Store indices of bad rows
exclude_indices = np.append(
    exclude_indices,
    bhk_df[bhk_df.price_per_sqft < stats['mean']].index.values
)


✔ Append those row indices
✔ We don’t delete yet — only mark

1 2️⃣ Remove all bad rows at once
return df.drop(exclude_indices, axis='index')


✔ Drops all illogical rows
✔ Returns cleaned dataset

🔹 REAL LIFE EXAMPLE
🔹 REAL LIFE EXAMPLE
| Location   | BHK | Price/sqft |
| ---------- | --- | ---------- |
| Whitefield | 1   | 6,000      |
| Whitefield | 2   | 5,000 ❌    |
| Whitefield | 3   | 7,500      |

2 BHK cheaper than 1 BHK = bad data

In [42]:
data=bhk_outlier_remover(data)

In [43]:
data.shape

(7361, 7)

In [44]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [45]:
data.drop(columns=['size','price_per_sqft'],inplace=True)

# claned DATA

In [46]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [47]:
# save cleaned data
data.to_csv('cleaned_data.csv')

In [48]:
X=data.drop(columns=['price'])
y=data['price']

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge # i will use these 3 model
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [50]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [77]:
X_test

                 location  total_sqft  bath  bhk
3865             Kadugodi      1150.0   2.0    2
6504         Sonnenahalli      1268.0   2.0    2
6417  Sector 7 HSR Layout      1162.0   2.0    2
3849             Kadugodi      1314.0   2.0    2
8615                other      1340.0   3.0    3
...                   ...         ...   ...  ...
9552                other      1080.0   2.0    2
1036           Begur Road      1200.0   2.0    2
5065         Marathahalli      1680.0   3.0    3
8457                other      1200.0   3.0    3
6738          Thanisandra      1702.0   3.0    3

[1473 rows x 4 columns]

In [51]:
print(X_train.shape)
print(X_test.shape)

(5888, 4)
(1473, 4)

In [79]:
print(X_train.columns)
print(X_test.columns)

Index(['location', 'total_sqft', 'bath', 'bhk'], dtype='object')
Index(['location', 'total_sqft', 'bath', 'bhk'], dtype='object')

## APPLYING LINEAR REGRESSION

In [ ]:
# DONT RUN THIS CODE

# 'location' only Column that was 'CATEGORICAL' so we use OHE

column_trans = make_column_transformer(
    (OneHotEncoder(sparse_output=False, handle_unknown='ignore'), ['location']),
    remainder='passthrough'
)

scaler=StandardScaler()
lr=LinearRegression()

pipe=make_pipeline(column_trans,scaler,lr)
# pipleline pe pehle column_tran ko pass kiya phir scalr and then phir lr

pipe.fit(X_train,y_train)

❌ Problem 1: StandardScaler after OneHotEncoder

Your pipeline:
ColumnTransformer → StandardScaler → LinearRegression


But:
OneHotEncoder produces 0/1 columns
Scaling 0/1 features is meaningless
It can distort interpretation and hurt stability

💡 Experts never scale one-hot encoded features

❌ Problem 2: Scaling should be column-wise

You want:
Scale numerical columns only
Encode categorical columns only

Right now:
Everything is scaled blindly

In [70]:
data

                  location  total_sqft  bath  price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.0    4
1      1st Block Jayanagar      1630.0   3.0  194.0    3
2      1st Block Jayanagar      1875.0   2.0  235.0    3
3      1st Block Jayanagar      1200.0   2.0  130.0    3
4      1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
10292                other      1200.0   2.0   70.0    2
10293                other      1800.0   1.0  200.0    1
10296                other      1353.0   2.0  110.0    2
10297                other       812.0   1.0   26.0    1
10300                other      3600.0   5.0  400.0    4

[7361 rows x 5 columns]

In [97]:
# BETTER WAY
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

# Define columns
categorical_cols = ['location']
numerical_cols = X_train.columns.drop('location')

# Column-wise preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', StandardScaler(), numerical_cols)
    ]
)

# Linear Regression pipeline
pipe_lr = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

# Train
pipe_lr.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('num', StandardScaler(),
                                                  Index(['total_sqft', 'bath', 'bhk'], dtype='object'))])),
                ('model', LinearRegression())])

In [ ]:
# predict
y_pred_lr=pipe_lr.predict(X_test)

In [99]:
r2_score(y_test,y_pred_lr)

0.823377245749841

# RIDGE REGRESSION

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge

categorical_cols = ['location']
numerical_cols = X_train.columns.drop('location')

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', StandardScaler(), numerical_cols)
    ]
)

# ridge Pipeline
pipe_ridge = Pipeline([
    ('preprocessor', preprocessor),
    ('model', Ridge(alpha=1.0))
])

# train
pipe_ridge.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('num', StandardScaler(),
                                                  Index(['total_sqft', 'bath', 'bhk'], dtype='object'))])),
                ('model', Ridge())])

In [103]:
# predict
y_pred_ridge = pipe_ridge.predict(X_test)

In [104]:
r2_score(y_test,y_pred_ridge)

0.8203010408114004

# using LASSO REGRESSION

In [106]:
# Lasso pipeline
pipe_lasso = Pipeline([
    ('preprocessor', preprocessor),
    ('model', Lasso(alpha=0.1, max_iter=10000))
])

# Train
pipe_lasso.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location']),
                                                 ('num', StandardScaler(),
                                                  Index(['total_sqft', 'bath', 'bhk'], dtype='object'))])),
                ('model', Lasso(alpha=0.1, max_iter=10000))])

In [107]:
# Predict
y_pred_lasso = pipe_lasso.predict(X_test)

In [108]:
r2_score(y_test,y_pred_lasso)

0.7863529641016644

In [109]:
print("NO Regularization", r2_score(y_test,y_pred_lr))
print("Ridge", r2_score(y_test,y_pred_ridge))
print("Lasso", r2_score(y_test,y_pred_lasso))

NO Regularization 0.823377245749841
Ridge 0.8203010408114004
Lasso 0.7863529641016644

In [110]:
import pickle

In [113]:
pickle.dump(pipe_ridge,open('RidgeModel.pkl','wb'))

🎯 WHY is this code used?

❌ Without Pickle
Model exists only in RAM
Jupyter close → model lost
Cannot deploy

✅ With Pickle
Model saved permanently
Can be reused anytime

Can be deployed to:
Flask
Django
FastAPI
Streamlit
Production servers